# Generated by Django 6.0.3 on 2026-03-19 21:25

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('commitment_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectShortAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('address', models.CharField(max_length=50)),
                ('state_address', models.CharField(help_text='Dhaka,BD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Facebook', max_length=50)),
                ('icon_class', models.CharField(help_text='fab fa-facebook-f', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FaqQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text=' <strong>I primarily work with <code>Python</code> and <code>Django</code></strong>, \n            along with front-end technologies like <code>HTML, CSS, JavaScript</code>.\n        ')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/images')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='core/pdfs')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='core/images')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Services', max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='fas fa-paper-plane', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='core/images')),
                ('button_text', models.CharField(default='View Projects', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='getintouch',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
