# Generated by Django 6.0.3 on 2026-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_connectsection_connectshortanswers_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectsection',
            options={'verbose_name_plural': 'Connect Section'},
        ),
        migrations.AlterModelOptions(
            name='connectshortanswers',
            options={'ordering': ['order'], 'verbose_name_plural': 'Connect Short Answer'},
        ),
        migrations.AlterModelOptions(
            name='contactlinks',
            options={'ordering': ['order'], 'verbose_name_plural': 'Contact Link'},
        ),
        migrations.AlterModelOptions(
            name='faqquestions',
            options={'verbose_name_plural': 'Faq Question'},
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Get In Touch'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name_plural': 'Introduction'},
        ),
        migrations.AlterModelOptions(
            name='serviceoptions',
            options={'ordering': ['order'], 'verbose_name_plural': 'Service Option'},
        ),
        migrations.AddField(
            model_name='contactlinks',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
