# Generated by Django 6.0.3 on 2026-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_connectsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='yt_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
