# Generated by Django 6.0.3 on 2026-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_intro_yt_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='wa_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
